#!/bin/bash

main() {
  genData | gpg -c > out/topology.gpg
}

genData() {
  echo "proxyUrl $(<vars/proxyUrl)"
  echo "listenPort $(<vars/listenPort)"
  echo "ipPrefix $(<vars/ipPrefix)"
  for p in {0..3}; do
    key=$(wg genkey)
    pubkey=$(echo $key | wg pubkey)
    echo "peer ${p} ${pubkey} ${key}"
  done
}

main
