kernel:
  image: linuxkit/kernel:5.6.11
  cmdline: "console=ttyS0 root=/dev/sda1"

init:
  - linuxkit/init:v0.8
  - linuxkit/runc:v0.8
  - linuxkit/containerd:v0.8

onboot:
  - name: sysctl
    image: linuxkit/sysctl:v0.8
  - name: rngd1
    image: linuxkit/rngd:v0.8
    command: ["/sbin/rngd", "-1"]
  - name: dhcpcd1
    image: linuxkit/dhcpcd:v0.8
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: wg
    image: ${WGLB_ID}
    capabilities: [all]
    net: host
    command: ['/setupNet.sh']
    env: ['TOPOLOGY=${TOPOLOGY}']
    
services:
  - name: rngd
    image: linuxkit/rngd:v0.8
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.8
  - name: getty
    image: linuxkit/getty:v0.8
    env:
     - INSECURE=true
  - name: sshd
    image: linuxkit/sshd:v0.8
    binds:
     - /root/.ssh/authorized_keys:/root/.ssh/authorized_keys
  - name: lb
    image: ${WGLB_ID}
    capabilities: [all]
    net: host
    command: ['/lb.sh']

files:
  - path: root/.ssh/authorized_keys
    source: id_rsa.pub
    mode: "0600"

trust:
  org:
    - linuxkit
    - cirslis
